kind: pipeline
name: CI
type: docker

trigger:
  event:
    - push
    - tag

volumes:
  - name: m2cache
    host:
      path: /app/.m2
steps:

  - name: build
    image: know-how.download/svc-builder:openjdk-17.0.2-slim
    pull: if-not-exists
    volumes:
      - name: m2cache
        path: /root/.m2
    environment:
      DEPLOYER_USERNAME:
        from_secret: DEPLOYER_USERNAME
      DEPLOYER_PASSWORD:
        from_secret: DEPLOYER_PASSWORD
    commands:
      - ./gradlew test jacocoTestReport --warning-mode all
      - ./gradlew -Pprod clean bootJar --warning-mode all
    when:
      event:
        - push
        - tag

  - name : notify-slack
    image : plugins/slack
    settings :
      webhook :
        from_secret : SLACK_WEBHOOK
      channel : dev
      template : >
        {{#success build.status}}
         :large_green_circle: :package: *${DRONE_COMMIT_MESSAGE}*
         {{build.link}} ({{build.branch}}) by {{build.author}}
        {{else}}
         :red_circle: :package: {{build.link}} ({{build.branch}}) by {{build.author}}
        {{/success}}
    when :
      status :
        - failure
        - success
    depends_on :
      - build
